name: Update badges from credly

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 */1 * *"
  pull_request:

jobs:
  update-readme:
    name: Update Readme with badges from credly
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.4.0
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREDLY_USER: hayrettin-ferhan-gedik
